### ISSUE TITLE
Doesn't Work?

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [hecomi/Unity-WebGL-3D-Chat#1]
When I opened index.html on my chromebook, it said:
![image](https://user-images.githubusercontent.com/112659665/198881354-e726a98d-7b17-4c40-b0be-822c922ddc7a.png)
Is there a way to enable Unity/WebGL on my device? If not, is there alternatives (like aframe)?

**Comment by hecomi** [comment]
Sorry for the late reply.

In order to try a WebGL build in local, you need to get an HTTP server up somehow - there is a mechanism in Unity to do this automatically when you do a WebGL build, but I have no idea how to do this on a Chromebook.

**Comment by TheRealDigitalMaster** [comment]
Ok 👍
